# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
#
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 22

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Rails/InverseOf:
  Enabled: false
