# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
#
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - 'config/**/*'
    - 'test/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# Style
#
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Layout
#
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#'] # ignored comment line

# Metrics
#
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

# Rails
#
Rails/InverseOf:
  Enabled: false

# RSpec
#
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
