language: ruby
cache: bundler
rvm:
- 2.6.5
services:
- postgresql
env:
  global:
  - CC_TEST_REPORTER_ID=c5fd8cd3e724b985885a522e2d5868567584983188d1b6230af994d47d82eb68
  - DATABASE_HOST=localhost
  - secure: KlPRlygM6iOu1s/buLxjQ/sN++zaxQSFmIeOAAVpg59C+TQk+gSPTGjfv0xyyZZAKltfIiYTaQPYoInZbdfTKDAJIGhAi47LJPlGmPNrXMa7bAqDQ67MGV4lr576OB1UNzh3J0YT3fyzjfnB7OHjROWWCBZiKsv5+DUXqTFbkxqzwSmaRNddv2HjOP3AVer1X/S3mQccFsKJNxTHi+P55Jx04O/CDlmJuslWmU5veu5RYRD8rJBoMjliHakBav1w1I08Td3E8c89nDGHZ/d++ZWZyDBy2fUo7LbtaSRqlv1mmhssesJI91TSCZf53N3yC3KE/1E0hHN4/90h77BgBu2tCEL0rw9/PAvGJVhxhkTD4b+RINR5+JWLyid9qyfkUuY3ckCcG7bqFa+VU4F2ZzzAX942YLXXxXwUE0n43dMIYckwlUMzeGOoL81ul0uY5B6ntsy8S8rnNRD6+Er2JsqEHDhyp8abRMQfu9ScJN3bxlhyqLFIT9hselZaUB9MSaAIK0batVWXZ657odT6q3VW5j/0FzLxGanEk1Y9HfJj1JmeD32qpPdHBDuYP6EP66e/FVGctf/D4w4bXim/AKB+qPup6HVSPD2h1pTyUQ2uZ3HGOtYwF5R8c5p8y43NSQcwv3CssLUt/7UiLnG3IbIT/D8ehca2dFi8EuPj05o=
addons:
  postgresql: 10
stages:
- lint
- security
- test
- docker
jobs:
  include:
  - stage: lint
    script:
    - gem install rubocop
    - bundle exec rubocop
  - stage: security
    script:
    - gem install brakeman
    - brakeman
    - gem install bundler-audit
    - bundle audit check --update
  - stage: test
    before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
    - bundle exec rake test
    - bundle exec rake spec
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEStrT_RESULT"
  - stage: docker
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_PROGESER_API .
    - docker push $DOCKER_PROGESER_API
    - docker build -f DockerfileSidekiq -t $DOCKER_PROGESER_SIDEKIQ .
    - docker push $DOCKER_PROGESER_API
    - docker push $DOCKER_PROGESER_SIDEKIQ
