version: '3.9'

services:
  db:
    image: postgres:15
    container_name: rails_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
    container_name: rails_app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
