version: '3.6'

services:
  db:
    restart: unless-stopped
    networks:
      - test-network
    image: postgres:latest

  web:
    restart: unless-stopped
    networks:
      - test-network
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  test-network:
    driver: bridge


