version: '3.6'

services:
  db:
    restart: unless-stopped
    networks:
      - test-network
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    networks:
      - test-network
    image: redis:5.0.7

  web:
    restart: unless-stopped
    networks:
      - test-network
    build: .
    volumes:
      - .:/myapp
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    environment:
        RAILS_ENV: development
    depends_on:
      - db
      - redis

  sidekiq:
    networks:
      - test-network
    build: .
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

networks:
  test-network:
    driver: bridge

volumes:
  gem_cache:
  db_data:
  node_modules:
