#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
docker build -t $DOCKER_PROGESER_API .
docker push $DOCKER_PROGESER_API
docker build -f DockerfileSidekiq -t $DOCKER_PROGESER_SIDEKIQ .
docker push $DOCKER_PROGESER_API
docker push $DOCKER_PROGESER_SIDEKIQ